version: "3.8"
services:
  anythingllm:
    image: mintplexlabs/anythingllm:latest # Wir nutzen das fertige Image!
    container_name: anythingllm
    ports:
      - "3001:3001"
    environment:
      - STORAGE_DIR=/app/server/storage
    volumes:
      - ./storage:/app/server/storage
      - ./env:/.env
    networks:
      - coolify
    restart: always

networks:
  coolify:
    external: true
